services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8301:80"
    volumes:
      - ./app:/var/www/html
      - ./data:/var/www/data
      - ./lib:/var/www/lib
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./data:/var/www/data
      - ./lib:/var/www/lib
